export const COVID_19 = [
  {
    file: "#WeWontRest in the fight against COVID-19 - May report (2).pdf",
    name: "#WeWontRest in the fight against COVID-19 - May report (2)",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "200319 CA JorgeAlcocer - COVID19.pdf",
    name: "200319 CA JorgeAlcocer - COVID19",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "200331 AI ListaReconversionHospitales COVID-19.pdf.pdf.pdf",
    name: "200331 AI ListaReconversionHospitales COVID-19.pdf.pdf",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "200401 AI ListaReconversionHospitales COVID-19.pdf.pdf.pdf",
    name: "200401 AI ListaReconversionHospitales COVID-19.pdf.pdf",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "20200413_Update_Coronavirus_ENG_img.pdf",
    name: "20200413_Update_Coronavirus_ENG_img",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "20200413_Update_Coronavirus_img.pdf",
    name: "20200413_Update_Coronavirus_img",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "2020_05_29_VES_salud.pdf",
    name: "2020_05_29_VES_salud",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file:
      "ACCIONES ESTRATÉGICAS DE LA COFEPRIS POR LA EMERGENCIA DE COVID-19 _ Comisión Federal para la Protección contra Riesgos Sanitarios _ Gobierno _ gob.mx.pdf",
    name:
      "ACCIONES ESTRATÉGICAS DE LA COFEPRIS POR LA EMERGENCIA DE COVID-19 _ Comisión Federal para la Protección contra Riesgos Sanitarios _ Gobierno _ gob.mx",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "ALIVIO SOLIDARIO.pdf",
    name: "ALIVIO SOLIDARIO",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "AMIIFTERING .pdf",
    name: "AMIIFTERING ",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "AMIIFTERING 8 ABRIL .pdf",
    name: "AMIIFTERING 8 ABRIL ",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Agenda n. 3_eng (1).pdf",
    name: "Agenda n. 3_eng (1)",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file:
      "Annex A_IFPMA Policy Principles on COVID-19 Vaccines Initiatives.pdf",
    name: "Annex A_IFPMA Policy Principles on COVID-19 Vaccines Initiatives",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "B4H digital health paper final.pdf",
    name: "B4H digital health paper final",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file:
      "BIAC Preliminary Considerations on the Trade Policy Response on Covid-19 01abr20 .pdf",
    name:
      "BIAC Preliminary Considerations on the Trade Policy Response on Covid-19 01abr20 ",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "COVID-19 FEDEFARMA 12Abril2020.pdf",
    name: "COVID-19 FEDEFARMA 12Abril2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file:
      "COVID-19 Human Capital Scenarios for Mexico_Final Presentation_14 May 2020.pdf",
    name:
      "COVID-19 Human Capital Scenarios for Mexico_Final Presentation_14 May 2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "COVID-19 RecomendacionesRegreso 5jun2020.pdf",
    name: "COVID-19 RecomendacionesRegreso 5jun2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "COVID-19 Resource Centre.pdf",
    name: "COVID-19 Resource Centre",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "COVID19-EducacioÌ_n-en-casa.pdf",
    name: "COVID19-EducacioÌ_n-en-casa",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "COVID19-NutricioÌ_n4.pdf",
    name: "COVID19-NutricioÌ_n4",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "COVID_19_Special_Report_2020_03_17_.01.pdf",
    name: "COVID_19_Special_Report_2020_03_17_.01",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Call to Action.Draft Statement_TC.pdf",
    name: "Call to Action.Draft Statement_TC",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Continuity of Care Collaboration FINAL.PDF",
    name: "Continuity of Care Collaboration FINAL",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Contribución IF en México COVID_CANIFARMA_mayo2020.pdf",
    name: "Contribución IF en México COVID_CANIFARMA_mayo2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "DRAFT_SLIDES_FIFARMA meeting 13 May_vF.pdf",
    name: "DRAFT_SLIDES_FIFARMA meeting 13 May_vF",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "DRAFT_SLIDES_FIFARMA meeting 13 May_vF[1].pdf",
    name: "DRAFT_SLIDES_FIFARMA meeting 13 May_vF[1]",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Dr. Bertalan Meskó, PhD.pdf",
    name: "Dr. Bertalan Meskó, PhD",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file:
      "Draft.Global Industry Commitment to Address Coronavirus Public Health Crisis.v1.pdf",
    name:
      "Draft.Global Industry Commitment to Address Coronavirus Public Health Crisis.v1",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file:
      "DuckerFrontier_LATAM-Healthcare Markets Outlook - Prepared for FIFARMA - 5.13.2020.pdf",
    name:
      "DuckerFrontier_LATAM-Healthcare Markets Outlook - Prepared for FIFARMA - 5.13.2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Ethos COVID19_Social Media pack.pdf",
    name: "Ethos COVID19_Social Media pack",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "GLOBAL COLLABORATION NEW COVID_19 TOOLS_Committment and Call.pdf",
    name: "GLOBAL COLLABORATION NEW COVID_19 TOOLS_Committment and Call",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Guía_de_continuidad_de_negocio_ICC.pdf",
    name: "Guía_de_continuidad_de_negocio_ICC",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid (1).pdf",
    name: "IFPMA Covid (1)",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 1 May.pdf",
    name: "IFPMA Covid-19 Update - 1 May",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 11 May.pdf",
    name: "IFPMA Covid-19 Update - 11 May",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 13 May.pdf",
    name: "IFPMA Covid-19 Update - 13 May",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 14 April.pdf",
    name: "IFPMA Covid-19 Update - 14 April",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 14 May.pdf",
    name: "IFPMA Covid-19 Update - 14 May",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 15 April.pdf",
    name: "IFPMA Covid-19 Update - 15 April",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 15 May.pdf",
    name: "IFPMA Covid-19 Update - 15 May",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 16 April.pdf",
    name: "IFPMA Covid-19 Update - 16 April",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 17 March.pdf",
    name: "IFPMA Covid-19 Update - 17 March",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 19 May.pdf",
    name: "IFPMA Covid-19 Update - 19 May",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 2 April.pdf",
    name: "IFPMA Covid-19 Update - 2 April",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 2 June.pdf",
    name: "IFPMA Covid-19 Update - 2 June",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 21 April.pdf",
    name: "IFPMA Covid-19 Update - 21 April",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 24 April.pdf",
    name: "IFPMA Covid-19 Update - 24 April",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 27 April.pdf",
    name: "IFPMA Covid-19 Update - 27 April",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 28 May.pdf",
    name: "IFPMA Covid-19 Update - 28 May",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 3 April.pdf",
    name: "IFPMA Covid-19 Update - 3 April",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 3 June.pdf",
    name: "IFPMA Covid-19 Update - 3 June",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 5 May.pdf",
    name: "IFPMA Covid-19 Update - 5 May",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 7 April.pdf",
    name: "IFPMA Covid-19 Update - 7 April",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update - 7 May.pdf",
    name: "IFPMA Covid-19 Update - 7 May",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid-19 Update -29 April.pdf",
    name: "IFPMA Covid-19 Update -29 April",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Covid.pdf",
    name: "IFPMA Covid",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Weekly COVID-19 Update_2020-04-06.pdf",
    name: "IFPMA Weekly COVID-19 Update_2020-04-06",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Weekly COVID-19 Update_2020-04-17.pdf",
    name: "IFPMA Weekly COVID-19 Update_2020-04-17",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Weekly COVID-19 Update_2020-04-24.pdf",
    name: "IFPMA Weekly COVID-19 Update_2020-04-24",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Weekly COVID-19 Update_2020-05-01.pdf",
    name: "IFPMA Weekly COVID-19 Update_2020-05-01",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA Weekly Update_2020-05-15.pdf",
    name: "IFPMA Weekly Update_2020-05-15",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA media briefings 2_3 Concept note 13 April 2020.pdf",
    name: "IFPMA media briefings 2_3 Concept note 13 April 2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file:
      "IFPMA_Statement_EU pledge_global_collaboration_COVID-19_4May2020_FINAL.pdf",
    name:
      "IFPMA_Statement_EU pledge_global_collaboration_COVID-19_4May2020_FINAL",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "IFPMA_Statement_IP__COVID-19_6 March 2020.pdf",
    name: "IFPMA_Statement_IP__COVID-19_6 March 2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file:
      "Informe Especial COVID19_ES (13abril2020)- Prioridades, actuaciones y resultados.pdf",
    name:
      "Informe Especial COVID19_ES (13abril2020)- Prioridades, actuaciones y resultados",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "LAA200420.pdf",
    name: "LAA200420",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "MA-CCC-Campaign-Members-Toolkit-1.pdf",
    name: "MA-CCC-Campaign-Members-Toolkit-1",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file:
      "Medicines Australia - Continuity of Care Collaboration - Media release.pdf",
    name:
      "Medicines Australia - Continuity of Care Collaboration - Media release",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Mensajes CSG 19mar20.pdf",
    name: "Mensajes CSG 19mar20",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Mensajes CSG 30mar20.pdf",
    name: "Mensajes CSG 30mar20",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Mensajes SRE_31mar20.pdf",
    name: "Mensajes SRE_31mar20",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "NEWSLETTER ALAFARPE - CORONAVIRUS - 13 DE ABRIL 2020.pdf",
    name: "NEWSLETTER ALAFARPE - CORONAVIRUS - 13 DE ABRIL 2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file:
      "New IQVIA Institute reports and COVID-19 resources now available.pdf",
    name: "New IQVIA Institute reports and COVID-19 resources now available",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "PhRMA_PrintAd1_v8 (2).pdf",
    name: "PhRMA_PrintAd1_v8 (2)",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Plan Coronavirus - Funsalud.pdf",
    name: "Plan Coronavirus - Funsalud",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Presentación AMIIF_200401.pdf",
    name: "Presentación AMIIF_200401",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Press release 4 May IFPMA Global Pledge FINAL.pdf",
    name: "Press release 4 May IFPMA Global Pledge FINAL",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Protocolos-COVID_CMABC.pdf",
    name: "Protocolos-COVID_CMABC",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Reactivación- Casos países.pdf",
    name: "Reactivación- Casos países",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Reg response FIFARMA .pdf",
    name: "Reg response FIFARMA ",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file:
      "Regreso a Actividades-Actividades divulgación y oficinas_01jun2020.pdf",
    name: "Regreso a Actividades-Actividades divulgación y oficinas_01jun2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file:
      "Regreso a Actividades-Reporte Recomendaciones y Acciones_01jun20.pdf",
    name: "Regreso a Actividades-Reporte Recomendaciones y Acciones_01jun20",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Regreso a Actividades_mayo2020.pdf",
    name: "Regreso a Actividades_mayo2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Reinicio de actividades por estado_130520.pdf",
    name: "Reinicio de actividades por estado_130520",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Reporte Semanal CIF Chile.13.04.2020.pdf",
    name: "Reporte Semanal CIF Chile.13.04.2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file:
      "Reporte de buenas prácticas ante la pandemia COVID-14 de mayo[2].pdf",
    name: "Reporte de buenas prácticas ante la pandemia COVID-14 de mayo[2]",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Resumen Especial Mar 2020.pdf",
    name: "Resumen Especial Mar 2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Semanal Covid 06-12 Abr 2020.pdf",
    name: "Semanal Covid 06-12 Abr 2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Semanal Covid 13-19 Abr 2020.pdf",
    name: "Semanal Covid 13-19 Abr 2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "Solution to COVID-19 Ventilator Shortage.pdf",
    name: "Solution to COVID-19 Ventilator Shortage",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file:
      "Special Report COVID19_EN (13april2020) FI Priorities, Actions and Outcomes.pdf",
    name:
      "Special Report COVID19_EN (13april2020) FI Priorities, Actions and Outcomes",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "WHO_Update-6_Regulation_Coronavirus_disease 2019_24042020.pdf",
    name: "WHO_Update-6_Regulation_Coronavirus_disease 2019_24042020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "WHO_Update-8_Regulation_Coronavirus_disease 2019_08May2020.pdf",
    name: "WHO_Update-8_Regulation_Coronavirus_disease 2019_08May2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "access draft programme_23Apr2020.pdf",
    name: "access draft programme_23Apr2020",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
  {
    file: "h05gbp-pdf-eng.pdf",
    name: "h05gbp-pdf-eng",
    description: "",
    content: "",
    metaTags: [],
    directoeryName: "COVID 19",
    path: "/Documents/covid-19",
  },
];
